### ISSUE TITLE
Multiple category selection issues

### ISSUE THREAD

**Issue by sjoonk** [nos3b3ar/admin-category-tree#1]
Works like charm, thank you.

But, when i select multiple categories on a post, it seems not working collectly.
For example, I have following categories:

- Photos
  -- Photos/Alpha
  -- Photos/Beta
- News
  -- News/Alpha
  -- News/Beta
- Errands
  -- Errands/Alpha
  -- Errands/Beta

In this case, when i select multiple categories like "Photos/Beta" and "News/Alpha",
this script seems not work collectly.

**Comment by sjoonk** [comment]
Sorry, my miss.

https://wordpress.org/plugins/admin-category-tree/#faq says:

> By default WordPress show all selected categories on top of the list. I don’t changed this behavior.

I got it!

**Comment by nos3b3ar** [comment]
Hi Kim,
yes, thats true. You got it.
Thanks for reply. Happy new Year :)
